baseURL = 'https://rusklabo.github.io'
languageCode = 'ja-jp'
title = 'RuskLabo_Blog'
theme = 'PaperMod'
 
[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    pre = "<i class='fa fa-heart'></i>"
    url = "/Search"
    weight = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
